-- Reviews table for vehicle reviews and ratings
CREATE TABLE public.reviews (
  review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  inv_id integer NOT NULL,
  account_id integer NOT NULL,
  review_title character varying(100) NOT NULL,
  review_text text NOT NULL,
  review_rating integer NOT NULL CHECK (review_rating >= 1 AND review_rating <= 5),
  review_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  is_approved boolean DEFAULT true,
  CONSTRAINT reviews_pkey PRIMARY KEY (review_id),
  CONSTRAINT fk_reviews_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) ON DELETE CASCADE,
  CONSTRAINT fk_reviews_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) ON DELETE CASCADE
);

-- Index for better performance
CREATE INDEX idx_reviews_inv_id ON public.reviews(inv_id);
CREATE INDEX idx_reviews_account_id ON public.reviews(account_id);
CREATE INDEX idx_reviews_approved ON public.reviews(is_approved);

-- Sample data
INSERT INTO public.reviews (inv_id, account_id, review_title, review_text, review_rating) VALUES
(1, 1, 'Amazing Vehicle!', 'This car exceeded all my expectations. Great performance and fuel efficiency.', 5),
(1, 1, 'Good Value', 'Decent car for the price. Some minor issues but overall satisfied.', 4),
(2, 1, 'Love It!', 'Best purchase I have ever made. Highly recommend to anyone looking for quality.', 5);